services:
  markgate_app:
    image: ghcr.io/runyournode/markgate:0.1.0
    container_name: markgate_app
    extra_hosts:  # if S3 is not in the stack
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"
    env_file:
      - .env.d/markgate.env
    depends_on:
     valkey:
          condition: service_healthy
    networks:
      - markgate-network-internal

  # Hard dependency : valkey (redis) used for locks
  valkey:
    image: docker.io/valkey/valkey:9.0.1-alpine3.23
    container_name: valkey
    expose:
      - "6379"
    ports:  # dev only
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: "valkey-server --save 60 1"
    healthcheck:
      test: "[ $$(valkey-cli ping) = 'PONG' ]"
      start_period: 5s
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    networks:
      - markgate-network-internal


  # Upstream processing backend : an example with docling-serve
  docling-serve:
    profiles:
      - dev-tools-docling
    image: ghcr.io/docling-project/docling-serve-cu128:v1.11.0
    container_name: docling-serve
    expose:
      - "5001"
    ports: # dev only
      - "5001:5001"
    env_file:
      - .env.d/dockling-serve.env
    volumes:
      - ${DOCLING_RUN}/.cache:/opt/app-root/src/.cache/:Z
    # deploy:  # This section is for compatibility with Swarm
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    runtime: nvidia
    restart: always
    networks:
      - markgate-network-internal

  paddleocr-vl-api:
    profiles:
      - dev-tools-paddle
    image: ccr-2vdh3abv-pub.cnc.bj.baidubce.com/paddlepaddle/paddleocr-vl:${API_IMAGE_TAG_SUFFIX}
    container_name: paddleocr-vl-api
    ports:
      - "8081:8080"
    depends_on:
      paddleocr-vlm-server:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ "0" ]
              capabilities: [ gpu ]
    # TODO: Allow using a regular user
    user: root
    restart: unless-stopped
    environment:
      - VLM_BACKEND=${VLM_BACKEND:-vllm}
    volumes:
      - ./mounts_config/paddle/pipeline_config_vllm.yaml:/home/paddleocr/pipeline_config_${VLM_BACKEND}.yaml
    command: /bin/bash -c "paddlex --serve --pipeline /home/paddleocr/pipeline_config_${VLM_BACKEND}.yaml"
    networks:
      - markgate-network-internal
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/health || exit 1" ]

  paddleocr-vlm-server:
    profiles:
      - dev-tools-paddle
    image: ccr-2vdh3abv-pub.cnc.bj.baidubce.com/paddlepaddle/paddleocr-genai-${VLM_BACKEND}-server:${VLM_IMAGE_TAG_SUFFIX}
    container_name: paddleocr-vlm-server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ "0" ]
              capabilities: [ gpu ]
    # TODO: Allow using a regular user
    user: root
    restart: unless-stopped
    networks:
      - markgate-network-internal
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/health || exit 1" ]
      start_period: 300s

volumes:
  redis_data:

networks:
  markgate-network-internal:
